### ISSUE TITLE
Exception: process 6 terminated with signal SIGKILL

### ISSUE THREAD

**Issue by utrivedi** [kishwarshafin/helen#32]
Hello, 

I am trying to run helen in polishing mode.  Here is my command:

`helen polish -i marginPolish_images -m helen_models/HELEN_r941_guppy344_microbial.pkl -o helen_polish/ -t 16`

However I face following error:
`Traceback (most recent call last):
  File "/lustre-gseg/software/bin/helen", line 33, in <module>
    sys.exit(load_entry_point('helen==0.0.23', 'console_scripts', 'helen')())
  File "/lustre-gseg/software/MarginPolish-HELEN/py36_venv/lib64/python3.6/site-packages/helen/helen.py", line 313, in main
    FLAGS.callers)
  File "/lustre-gseg/software/MarginPolish-HELEN/py36_venv/lib64/python3.6/site-packages/helen/modules/python/PolishInterface.py", line 87, in polish_genome
    callers)
  File "/lustre-gseg/software/MarginPolish-HELEN/py36_venv/lib64/python3.6/site-packages/helen/modules/python/CallConsensusInterface.py", line 153, in call_consensus
    callers, threads_per_caller, num_workers)
  File "/lustre-gseg/software/MarginPolish-HELEN/py36_venv/lib64/python3.6/site-packages/helen/modules/python/models/predict_cpu.py", line 248, in predict_cpu
    join=True)
  File "/lustre-gseg/software/MarginPolish-HELEN/py36_venv/lib64/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/lustre-gseg/software/MarginPolish-HELEN/py36_venv/lib64/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/lustre-gseg/software/MarginPolish-HELEN/py36_venv/lib64/python3.6/site-packages/torch/multiprocessing/spawn.py", line 108, in join
    (error_index, name)
Exception: process 6 terminated with signal SIGKILL`

Please could you shed some light on this? 

Many thanks in advance.

**Comment by kishwarshafin** [comment]
@utrivedi , 

I'll look into this. In parallel, would you mind using PEPPER for now? We have tested PEPPER on many samples and they produce very similar results to `MarginPolish-HELEN` and it's lightweight too:
https://github.com/kishwarshafin/pepper/releases/tag/v0.1

**Comment by utrivedi** [comment]
Thank you @kishwarshafin . I am happy to try pepper but it doesn't seem to have a model that would fit my data that is **minion r941 g344 HAC**. Any suggestions to overcome this problem are very welcome.

**Comment by kishwarshafin** [comment]
Hi @utrivedi ,

You can use `PromethION_r941_guppy305_HAC_microbial.pkl` with your 3.4.4 data. We have tested this model on promethION and minION and it works similarly. The `guppy305` part indicates the lowest supported version of guppy for that model. We have tested it for every version between 3.0.5 and 4.2.2 and the model shows no difference in performance.

**Comment by utrivedi** [comment]
That's great. Thanks @kishwarshafin. By the way, I figured out that the earlier error was because it was running out of RAM. The instance was launched again with higher RAM and it works now. :)

**Comment by kishwarshafin** [comment]
Ah, pheww, thanks. I was going to report that I can't re-generate the error. Thank you, I'm closing this issue. :)
